### ISSUE TITLE
Fix slider tooltip not showing in mobile browsers

### ISSUE THREAD

**Issue by MasterPIC** [OctoPrint/OctoPrint#2412]
By smartphone while moving any slider it's not possible to read the current value.
Maybe adding a label is a good workaround.

Thanks
Armando

**Comment by ntoff** [comment]
What do you mean? There's already labels on the buttons built into octoprint's control page. Are you talking about custom controls? Plugins?

Have you thought about using the TouchUI plugin? It's optimised for touch interfaces.

**Comment by MasterPIC** [comment]
By adding a slider in config.yaml (*) no numeric value is shown when on smartphone..
When on PC I see the current numeric value while moving the slider.
I think it's worth making the slider working as expected also on a smartphone.

@ntoff Thank you for your tip: I didn't know TouchUI plugin!

( * ) This is the kind of code added in config.yaml:
```
- input:
  - default: 150
    name: Size
    parameter: dim
    slider:
      max: 210
      min: 50
      step: 5
  name: Calibration
  script: Calibrate.gco

```
