### ISSUE TITLE
[feature request] Toggle - Webcam Stream on Control Page

### ISSUE THREAD

**Issue by ghost** [OctoPrint/OctoPrint#368]
It would be convenient to have an option to toggle the webcam stream on and off of the control page.  The control page seems to crash the Android browser after a few minutes on my Nook Color.  It may also help with latency when controlling the printer.  I might be able to figure out how to add it, but thought others may experience the same issue and decided to if a feature request was appropriate.  Loving OctoPrint btw. +10 foosel

**Comment by jneilliii** [comment]
can't this be accomplished with system commands in config.yaml and start/stop service?

```
system:
  actions:
  - action: startwebcam
    command: sudo service webcamd start
    name: Start Webcam
  - action: stopwebcam
    command: sudo service webcamd stop
    name: Stop Webcam
```
