### ISSUE TITLE
allowCrossOrigin=true but API still only reachable on localhost

### ISSUE THREAD

**Issue by OevreFlataeker** [OctoPrint/OctoPrint#3717]
#### What were you doing?

Trying to expose the API to hosts outside of octoprint system. The option "Allow Cross Origin Resource Sharing" has been enabled and Octoprint has been restarted.

The config file shows the value set to true:
```
pi@octopi:~/.octoprint $ head config.yaml 
accessControl:
    salt: xxxx
api:
    allowCrossOrigin: true
    key: xxxx
plugins:
    _disabled:
    - touchui
    - SpoolManager
    - kronos_data_collector
...
``` 
however the port for the API is still bound to localhost after a restart of octoprint and is thus not available to the outside
```
pi@octopi:~/.octoprint $ netstat -anpA inet | grep :5000
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      7471/python2        
tcp        0      0 127.0.0.1:60130         127.0.0.1:5000          ESTABLISHED -                   
tcp        0      0 127.0.0.1:5000          127.0.0.1:60130         ESTABLISHED 7471/python2        
```
#### What did you expect to happen?

API will listen on 0.0.0.0:5000
#### What happened instead?

API still listens on 127.0.0.1:5000

#### Did the same happen when running OctoPrint in safe mode?

Yes

#### Version of OctoPrint

1.4.2 on octopi 0.15.1

#### Operating System running OctoPrint

OctoPi 0.15.1

#### Printer model & used firmware incl. version

Anycubic i3 Mega

#### Browser and version of browser, operating system running browser

Chrome, Linux/Windows

#### Link to octoprint.log

https://pastebin.com/Q1h6K4xu

#### Link to contents of terminal tab or serial.log

https://pastebin.com/dFEMm3Hu

#### Link to contents of Javascript console in the browser

n/a

#### Screenshot(s)/video(s) showing the problem:

n/a

I have read the FAQ.
