### ISSUE TITLE
getAdditionalControls regex and template don't work

### ISSUE THREAD

**Issue by jneilliii** [OctoPrint/OctoPrint#3759]
#### What were you doing?

Trying to assist a user on the community forum [here](https://community.octoprint.org/t/trying-to-get-positional-data-with-m114/24832?u=jneilliii) with getAdditionalControls and regex template matching, came to the conclusion that it does not work as expected. The regex is not seen/matched and output is not displayed on the UI when the button is pressed.

Example config.yaml.
```
controls:
-   children:
    -   command: M114
        name: Get Position
        regex: X:([-+]?[0-9.]+) Y:([-+]?[0-9.]+) Z:([-+]?[0-9.]+) E:([-+]?[0-9.]+)
        template: 'Position: X={0}, Y={1}, Z={2}, E={3}'
    name: Reporting
```

equivalent getAdditionalControls callback.

```
self.getAdditionalControls = function () {
    return [{
            name: 'Reporting',
            children: [{
                    command: 'M114',
                    name: 'Get Position',
                    regex: 'X:([-+]?[0-9.]+) Y:([-+]?[0-9.]+) Z:([-+]?[0-9.]+) E:([-+]?[0-9.]+)',
                    template: 'Position: X={0}, Y={1}, Z={2}, E={3}',
                }
            ]
        }
    ];
}
```

#### What did you expect to happen?

To work exactly the same way that Custom Controls work from config.yaml.

#### What happened instead?

Command is sent, but template is not filled out and displayed.

#### Did the same happen when running OctoPrint in safe mode?

Can't reproduce without a plugin.

#### Version of OctoPrint

1.4.2

#### Operating System running OctoPrint

OctoPi 0.18, Python 3.7.3

#### Printer model & used firmware incl. version

Virtual Printer

#### Browser and version of browser, operating system running browser

Google Chrome Version 85.0.4183.121 (Official Build) (64-bit)

#### Link to octoprint.log

N/A

#### Link to contents of terminal tab or serial.log

N/A

#### Link to contents of Javascript console in the browser

No errors.

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.
