### ISSUE TITLE
Rate limits too aggressive for print farms

### ISSUE THREAD

**Issue by shapecoder** [OctoPrint/OctoPrint#4006]
**The problem**

1. Buy 22 3D-printers and set each one up with a separate instance of Octoprint
2. Update the first 8 or so
3. When navigating to Software Update, all plugins will now feature an exclamation mark accompanied with the following text: Rate limit exceeded while checking for update, please try again later

**Did the issue persist even in safe mode?**

Yes, it did persist

**Version of OctoPrint**

1.5.2+

**Operating system running OctoPrint**

OctoPi

**Printer model & used firmware incl. version**

Prusa MK3S 3.9.3

**Browser and version of browser, operating system running browser**

Vivaldi 3.6.2165.36, Windows 10 1909 18363.1316

**Checklist of files to include below**

- [X] octoprint.log
- [ ] serial.log or contents of your terminal tab (always include in cases of issues with printer communication)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

[octoprint.log](https://github.com/OctoPrint/OctoPrint/files/5936614/octoprint.log)

![image](https://user-images.githubusercontent.com/28315419/107115335-42b75580-686c-11eb-82b4-041d78d88ecd.png)

**Comment by cp2004** [comment]
These rate limits are outside of our control, they are set by Github for anonymous API usage. You're limited to ~60 requests per hour.

There is a solution though, you can create a Github token and add it to config.yaml so that the software update plugin can use it to authenticate, then the limit is ~5000 per hour - should be enough.

[The docs on this are here,](https://docs.octoprint.org/en/master/bundledplugins/softwareupdate.html#configuring-the-plugin), for example:
```yaml
plugins:
  softwareupdate:
    # global credentials to provide to version checks
    credentials:

      # GitHub API token to use for the github_release and github_commit version checks.
      # Helpful if you regularly run into rate limit issues with the GitHub API using
      # the default anonymous access. Use a personal access token:
      #   https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token
      # Unset by default
      github: MYGITHUBTOKEN
```
There's also a thread on the community forums [here](https://community.octoprint.org/t/cannot-update-rate-limit-exceeded/30258/8?u=charlie_powell) if you need more information about finding config.yaml.

Hopefully that helps.
