### ISSUE TITLE
gcodeviewer ignored in config.yaml appearance-->components items

### ISSUE THREAD

**Issue by synman** [OctoPrint/OctoPrint#4343]
### The problem

Apologies for not catching the version this regressed in.  I'm going to guess it was somewhere between 1.4 and 1.5.  

We've lost the ability to disable and reorder the gcode tab via appearance/components/disabled and order.   This syntax works fine for all other tabs but, as stated above, about a year ago this broke.  Apologies for not reporting this sooner.  I opened an issue on my own plugin when I first detected it back in January 2021 and just now got around to looking into it.

https://github.com/synman/Octoprint-Bettergrblsupport/issues/32

I tried variations on "gcodeviewer" thinking maybe you changed the name to something like "gcode" but that did not make a difference after putzing around with it this evening.

```
appearance:
  color: black
  components:
    disabled:
      tab:
      - temperature
      - control
      - gcodeviewer
    order:
      tab:
      - plugin_bettergrblsupport
      - temperature
      - control
      - gcodeviewer
      - terminal
      - timelapse
```
   

### Did the issue persist even in safe mode?

Yes, it did persist

### If you could not test in safe mode, please state why

validated as broken in safe mode too

### Version of OctoPrint

1.7.2

### Operating system running OctoPrint

OctoPi 0.16.0

### Printer model & used firmware incl. version

Eleksmaker A3 Laser Engraver (GRBL)

### Browser and version of browser, operating system running browser

Latet Safari, OSX Monteray 

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [X] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

This is pretty cut and dry.  I'm more than happy to supply additional details but am unsure how any of the items listed here would prove helpful.
[octoprint-systeminfo-20211212213300.zip](https://github.com/OctoPrint/OctoPrint/files/7700581/octoprint-systeminfo-20211212213300.zip)
