### ISSUE TITLE
Controls configuration being routinely wiped out

### ISSUE THREAD

**Issue by AapoTahkola** [OctoPrint/OctoPrint#4585]
### The problem

The custom control buttons defined in config as:
```
controls:
- children:
    - children:
      - commands:
        - M300 S100 P300 ; beep
        - M290 Z0.25
        confirm: null
        name: 0.25 baby up
```
Are routinely removed by "someone" presumably by octoprint. This has happened three times already and I am getting tired of having to rewrite them.

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### If you could not test in safe mode, please state why

no other plugins enabled, it should work in normal mode

### Version of OctoPrint

1.8.1

### Operating system running OctoPrint

raspbian

### Printer model & used firmware incl. version

Marlin bugfix-2.1.x

### Browser and version of browser, operating system running browser

firefox

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20220718233853.zip](https://github.com/OctoPrint/OctoPrint/files/9135618/octoprint-systeminfo-20220718233853.zip)
