### ISSUE TITLE
[Request] Add support for higher resolution displays

### ISSUE THREAD

**Issue by barkermn01** [OctoPrint/OctoPrint#4914]
### Is your feature request related to a problem? Please describe.

When using a 1440p screen the octopi does feel the right size it's also harder to use

### Describe the solution you'd like

implement the following CSS into the CSS
```css
@media screen and (min-width: 1400px) {
    
    .container, .navbar-static-top .container {
        width: 1280px;
    }
    
    .tabbable.span8 {width: 940px;}
    
    .jog-panel {
        margin-right: 10%;
        width:40%;
        
    }
    
    .jog-panel#control-jog-extrusion{
        margin-right: 10%;
        width:15%
    }
    
    .jog-panel#control-jog-general{
        margin-right: 10%;
        width:15%
    }
    
    div#control-jog-extrusion {
        margin: auto;
    }
    
    div#control-jog-general {
        margin: auto;
    }
    
    button#control-yinc{
        margin-left: 25px;
    }
    
    button#control-xdec.pull-left {
        margin-left: 25px;
    }
    
    button#control-ydec {
        margin-left: 25px;
    }
}
```

### Describe alternatives you've considered

not applicable

### Additional context

i have built this using the web inspector on my browser so i know it's good
