### ISSUE TITLE
[1.10.0rc2] Verify handling of external users vs reauthentication checks

### ISSUE THREAD

**Issue by foosel** [OctoPrint/OctoPrint#4966]
### The Problem

Curious what the expected outcome of the new re-authentication mechanism relative to the following config? Since there is no actual user created manually the password was never set due to addRemoteUsers. Since I don't know the password I can't change it either as the end user. 

```
accessControl:
  addRemoteUsers: true
  remoteUserHeader: whatever-header
  trustRemoteUser: true
```

_Originally posted by @jneilliii in https://github.com/OctoPrint/OctoPrint/issues/4948#issuecomment-1962251101_

### Solution

Ensure that external logins are treated as "always freshly checked", like API keys. This might already be the case but needs to be verified, hence the "triage" label.
