### ISSUE TITLE
Metadata pre-processing doesn't work with gcode files containing whitespaces in their filenames.

### ISSUE THREAD

**Issue by ofoxus** [OctoPrint/OctoPrint#5008]
### The problem

When uploading a gcode file containing a whitespace, the metadata processor won't be able to execute the octoprint analysis code. E.g. I tried printing a file called `CFFFP_medium paint palette.gcode` (from Cura):
`/usr/local/bin/python -m octoprint analysis gcode --speed-x=15000 --speed-y=15000 --max-t=10 --throttle=0.0 --throttle-lines=100 --bed-z=0.0 /octoprint/octoprint/uploads/CFFFP_medium paint palette.gcode`
This fails with the following error:
```
Usage: octoprint analysis gcode [OPTIONS] PATH
Try 'octoprint analysis gcode --help' for help.

Error: Got unexpected extra arguments (paint palette.gcode)
```

Expected result (I added the missing quotes manually):
```
# /usr/local/bin/python -m octoprint analysis gcode --speed-x=15000 --speed-y=15000 --max-t=10 --throttle=0.0 --throttle-lines=100 --bed-z=0.0 "/octoprint/octoprint/uploads/CFFFP_medium paint palette.gcode"
DONE:1.0590811959991697s
RESULTS:
dimensions:
  depth: 168.88
  height: 2.2
  width: 183.256
extrusion_length:
- 5866.855039999981
extrusion_volume:
- 0.0
printing_area:
  maxX: 183.256
  maxY: 163.88
  maxZ: 2.2
  minX: 0.0
  minY: -5.0
  minZ: 0.0
total_time: 117.87162016083214
travel_area:
  maxX: 200.0
  maxY: 220.0
  maxZ: 10.0
  minX: 0.0
  minY: -5.0
  minZ: 0.0
travel_dimensions:
  depth: 225.0
  height: 10.0
  width: 200.0
```

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.10.0

### Operating system running OctoPrint

Linux - Raspberry Pi OS Lite (64-bit)

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [X] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

Systeminfo Bundle:
[octoprint-systeminfo-20240505121238.zip](https://github.com/OctoPrint/OctoPrint/files/15212901/octoprint-systeminfo-20240505121238.zip)

GCODE file used:
[CFFFP_medium paint palette.zip](https://github.com/OctoPrint/OctoPrint/files/15212911/CFFFP_medium.paint.palette.zip)

I already intend on creating a pull request for the problem, as it is relatively easy to fix.
