### ISSUE TITLE
UI / Switching to a profile with more than one extruder does not set number of extruders on virtual printer correctly

### ISSUE THREAD

**Issue by WildRikku** [OctoPrint/OctoPrint#5118]
### The problem

1. Turn on virtual printer in virtual printer plugin settings
2. Create printer profile with extruder count > 1, shared nozzle
3. Select profile in connection settings and connect to VIRTUAL
4. Some things will show extruder count correctly (e.g. SpoolManager)
5. GCode with T commands > 0 will be rejected
6. Check config.yaml, the virtual printer section does not have a numExtruder entry
7. Adding that entry fixes no. 5

I did not test this without "shared nozzle".

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.10.3

### Operating system running OctoPrint

SteamOS

### Printer model & used firmware incl. version

VIRTUAL

### Browser and version of browser, operating system running browser

SteamOS x Firefox 136.0

### Checklist of files to include below

- [x] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [x] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20250306180206.zip](https://github.com/user-attachments/files/19112525/octoprint-systeminfo-20250306180206.zip)

Test gibberish GCode

```
G1 E-2 F1200
G0 Z5.05 F20000  ; move nozzle to remove stringing
G0 X215 Y357  ; parking toolhead xy
G0 Z4.5 ;  parking toolhead z

M109 S200  ; Tool Change Tool Temp

T3 ; MMU Toolchange Command

M109 S240  ; set temp for now current tool for Octoprint to modify

G0 X175 Y357  ; Safe zone
G0 Z5.05  ; current layer height

; pseudo blabla
G2 X162.111553 Y182.841685 I-8.273634 J-14.45124 E0.028085
G1 F10288.471
G2 X163.020429 Y182.197513 I-6.235748 J-9.761412 E0.06031
G1 F9765.9069
G1 X163.311532 Y181.97433 E0.020912
G1 X163.622204 Y181.721883 E0.022823
G1 F8586.8647
G1 X163.932875 Y181.469436 E0.025956
G1 X164.014276 Y181.400536 E0.006915

G4 P5000

G1 E-2 F1200
G0 Z5.05 F20000  ; move nozzle to remove stringing
G0 X215 Y357  ; parking toolhead xy
G0 Z4.5 ;  parking toolhead z

M109 S200  ; Tool Change Tool Temp

T0 ; MMU Toolchange Command

M109 S240  ; set temp for now current tool for Octoprint to modify

G0 X175 Y357  ; Safe zone
G0 Z5.05  ; current layer height

; pseudo blabla
G2 X162.111553 Y182.841685 I-8.273634 J-14.45124 E0.028085
G1 F10288.471
G2 X163.020429 Y182.197513 I-6.235748 J-9.761412 E0.06031
G1 F9765.9069
G1 X163.311532 Y181.97433 E0.020912
G1 X163.622204 Y181.721883 E0.022823
G1 F8586.8647
G1 X163.932875 Y181.469436 E0.025956
G1 X164.014276 Y181.400536 E0.006915

G4 P5000

G1 E-2 F1200
G0 Z5.05 F20000  ; move nozzle to remove stringing
G0 X215 Y357  ; parking toolhead xy
G0 Z4.5 ;  parking toolhead z

M109 S200  ; Tool Change Tool Temp

T1 ; MMU Toolchange Command

M109 S240  ; set temp for now current tool for Octoprint to modify

G0 X175 Y357  ; Safe zone
G0 Z5.05  ; current layer height

; pseudo blabla
G2 X162.111553 Y182.841685 I-8.273634 J-14.45124 E0.028085
G1 F10288.471
G2 X163.020429 Y182.197513 I-6.235748 J-9.761412 E0.06031
G1 F9765.9069
G1 X163.311532 Y181.97433 E0.020912
G1 X163.622204 Y181.721883 E0.022823
G1 F8586.8647
G1 X163.932875 Y181.469436 E0.025956
G1 X164.014276 Y181.400536 E0.006915

G4 P5000

```

config.yaml

```
api:

appearance:
  closeModalsWithClick: false
  defaultLanguage: de
  fuzzyTimes: false
feature:
  modelSizeDetection: false
gcodeAnalysis:
  runAt: always
plugins:
  SpoolManager:
    bedOffsetEnabled: true
    databaseName: mysql
    databasePassword: my-secret-pw
    databasePort: '8080'
    databaseType: mysql
    databaseUser: root
    importCSVMode: replace
    selectedSpoolsDatabaseIds:
    - 3
    - 9
    - 6
    - 7
    toolOffsetEnabled: true
  _disabled:
  - achievements
  announcements:
    _config_version: 1
    channels:
      _blog:
        read_until: 1723634700
      _important:
        read_until: 1698310200
      _octopi:
        read_until: 1684929600
      _plugins:
        read_until: 1724803200
      _releases:
        read_until: 1718697600
  classicwebcam:
    _config_version: 1
  discovery:

  errortracking:

  gcodeviewer:
    _config_version: 1
  plotlytempgraph:
    _config_version: 5
  pluginmanager:
    repository_restricted: false
  softwareupdate:
    _config_version: 9
    checks:
      SpoolManager:
        prerelease: true
        prerelease_channel: testing
      helloworld:
        current: 150bda4635fe8e032334d67a4554e6289d5c500a
        prerelease: true
        prerelease_channel: notmain
  tracking:
    enabled: false

  virtual_printer:
    _config_version: 1
    enabled: true
    numExtruders: 4 (this is the line I added manually)
printerProfiles:
  default: _default
serial:
  autoconnect: true
  baudrate: 115200
  port: VIRTUAL
server:
  firstRun: false
  onlineCheck:
    enabled: true
  pluginBlacklist:
    enabled: true
  seenWizards:
    backup: null
    classicwebcam: 1
    corewizard: 4
    file_check: 1
    tracking: null
temperature:
  profiles:
  - bed: 100
    chamber: null
    extruder: 210
    name: ABS
  - bed: 60
    chamber: null
    extruder: 180
    name: PLA
  - bed: 80
    chamber: 0
    extruder: 240
    name: PETG
```
