### ISSUE TITLE
Problem with System Tab

### ISSUE THREAD

**Issue by borsti87** [OctoPrint/OctoPrint#518]
Hi,

I would like to switch my 3D-Printer on/off and shutdown/reboot my raspi via octoprint so I have made following changes in my config.yaml:

```
system:
  actions:
  - action: shutdown
    command: sudo shutdown -h now
    confirm: You are about to shutdown the system.
    name: Shutdown
  - action: reboot
    command: sudo shutdown -r now
    confirm: You are about to reboot the system
    name: Reboot
  - action: printeron
    command: gpio mode 7 out
    confirm: You are turn on printer
    name: Turn printer on
  - action: printeroff
    command: gpio mode 7 in
    confirm: You are turn off printer
    name: Turn off printer
```

but if I click on the System tab, there is an empty dropdown menu.

Here are links to 
- config.yaml http://pastebin.com/ucF4E7fE
  and 
- octoprint.log http://pastebin.com/HdR1LshR

My octoprint vesion is: 1.2.0-dev-79-gbe99c59

Thank you for help
Best regards
borsti87
