### ISSUE TITLE
Cannot Enable Timelapse for IP Cam [Support]

### ISSUE THREAD

**Issue by ssshake** [OctoPrint/OctoPrint#616]
I'm using an ip cam for my webcam which seems to work just fine for streaming but I cant get it to work for timelapse snapshots.

```
webcam:
  ffmpeg: /usr/bin/avconv
  snapshot: http:/10.0.0.22/image.jpg
  stream: http://10.0.0.22/mjpeg.cgi
  watermark: false
```

![timelapseissue](https://cloud.githubusercontent.com/assets/1675868/4635356/b822fc70-53d8-11e4-8e3d-a514aae2bb76.png)

I've been able to enable it through my phone, I presume because my phone's browser doesnt support the javascript that disabled the drop down. And when I do I end up with several hundred megabyte JPG images in the timelapse/tmp folder. Very strange. What's going on here?

Also is there a way to improve the logging for octoprint, currently I find it rather absent which makes it really hard to understand whats happening under the hood.
1. Branch & Commit or Version:

got version from git {'version': '1.1.0-7-g62a51bb', 'branch': 'master', 'full': '62a51bb06131dc839cc52e6d30a5300b94ed6bc1'}
Version is currently: 1.1.0-7-g62a51bb

"I love cookies"
